import React from 'react';
import { Loader, FormField, Card } from '../components';
const Home = () => {
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-sans font-bold text-[#000000] text-[32px]'>
          The Community Showcase
        </h1>
        <p className='mt-2 text-[#666375] max-w-[500px] text-[16px]'>
          Browse through a collection of imaginative and stunning images generated by DALL-E AI
        </p>

      </div>




    </section>
  )
}

export default Home
