import React, { useEffect, useState } from 'react';
import { Loader, FormField, Card } from '../components';


const RenderCards = ({ title, data }) => {
  if (data && data.length > 0) {
    return data.map((post) => <Card key={post._id}{...post} />)
  }
  return (
    <h2 className='mt-5 font-bold text-black text-xl uppercase'>
      {title}
    </h2>
  )
}



const Home = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState('');

  useEffect(() => {
    const fetchPosts = async () => {
      setIsLoading(true)
      try {
        const response = await fetch("http://localhost:8000/api/v1/post", {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json'
          },
        })
        if (response.ok) {
          const result = await response.json();
          setAllPosts(result.data.reverse())
        }


      } catch (error) {
        alert(error)

      } finally {
        setIsLoading(false)
      }
    }

    fetchPosts();
  }, [])
  console.log("All posts==>", allPosts)

  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-sans font-bold bg-clip-text bg-gradient-to-br from-blue-500 to-pink-500 text-transparent text-[42px]'>
          The Community Showcase
        </h1>
        <p className='mt-2 text-[#666375] max-w-[500px] text-[16px]'>
          Browse through a collection of imaginative and stunning images generated by DALL-E AI
        </p>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        {isLoading ? (
          <div className='flex justify-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing Results for
                <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 cs:grid-cols-2 grid-cols-1 gap-3'>
              {searchText ? (
                <RenderCards
                  title="No Search Results Found"
                  data={[]}
                />
              ) : (
                <RenderCards
                  title="No Posts Found"
                  data={allPosts}
                />
              )}
            </div>
          </>
        )}
      </div>




    </section>
  )
}

export default Home
